services:
  mongodb:
    image: mongo:7.0
    container_name: instagram
    restart: unless-stopped
    ports:
      - "27016:27017"
    environment:
      MONGO_INITDB_ROOT_USERNAME: hoanghuy04
      MONGO_INITDB_ROOT_PASSWORD: 123
    volumes:
      - mongodb_data:/data/db
      - ./mongo-init:/docker-entrypoint-initdb.d
    networks:
      - socialtrio-network
    healthcheck:
      test: ["CMD", "mongosh",
             "--username=hoanghuy04",
             "--password=123",
             "--eval", "db.adminCommand('ping')",
             "--authenticationDatabase=admin"]
      interval: 30s
      timeout: 10s
      retries: 5
      start_period: 30s

volumes:
  mongodb_data:

networks:
  socialtrio-network:
    driver: bridge
